# Generated by Django 4.1.3 on 2022-11-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cabinet_no', models.CharField(max_length=4)),
                ('time', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('prifile', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
