# Generated by Django 4.1.3 on 2022-11-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_staff_user_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=30)),
                ('db_password', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CureDAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CureData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CureEntity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorCardDAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorCardData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cabinet_no', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=12)),
                ('time', models.CharField(max_length=4)),
                ('staff_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorCardEntity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hospital_title', models.CharField(max_length=100)),
                ('doctor_speciality', models.CharField(max_length=50)),
                ('cabinet_no', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=12)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sections', models.CharField(max_length=40)),
                ('info', models.TextField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalEntity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('sections', models.CharField(max_length=40)),
                ('info', models.TextField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCardDAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCardData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=5)),
                ('passport_data', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCardEntity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=5)),
                ('passport_data', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTestDAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTestData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hospital_title', models.CharField(max_length=100)),
                ('cabinet_no', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=12)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTestEntity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('hospital_title', models.CharField(max_length=100)),
                ('cabinet_no', models.CharField(max_length=4)),
                ('date', models.CharField(max_length=12)),
                ('time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='RegionDAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RegionData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('country', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionEntity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('is_country', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_access', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StaffData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('hospital_title', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_access', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('admin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.CreateModel(
            name='StaffEntity',
            fields=[
                ('userentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hospital.userentity')),
                ('cabinet_no', models.CharField(max_length=4)),
                ('time', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('hospital_title', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=50)),
            ],
            bases=('hospital.userentity',),
        ),
        migrations.AddField(
            model_name='userdao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.userdata'),
        ),
        migrations.AddField(
            model_name='staffdao',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.staffdata'),
        ),
        migrations.AddField(
            model_name='regiondao',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.regiondata'),
        ),
        migrations.AddField(
            model_name='medicaltestdao',
            name='med_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medicaltestdata'),
        ),
        migrations.AddField(
            model_name='medicalcarddao',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medicalcarddata'),
        ),
        migrations.AddField(
            model_name='hospitaldao',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitaldata'),
        ),
        migrations.AddField(
            model_name='doctorcarddao',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctorcarddata'),
        ),
        migrations.AddField(
            model_name='curedao',
            name='cure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.curedata'),
        ),
    ]
