# Generated by Django 4.1.3 on 2022-11-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_configures_curedao_curedata_cureentity_doctorcarddao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_table', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('admin', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('staff_table', models.CharField(max_length=50)),
                ('staff_id', models.IntegerField()),
                ('speciality', models.CharField(max_length=50)),
                ('hospital_title', models.CharField(max_length=100)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_phone', models.CharField(max_length=12)),
                ('staff_email', models.CharField(max_length=30)),
                ('staff_password', models.CharField(max_length=50)),
                ('medical_card_table', models.CharField(max_length=50)),
                ('mc_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=5)),
                ('passport_data', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('region_id', models.IntegerField()),
                ('region_title', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('cure_id', models.IntegerField()),
                ('cure_title', models.CharField(max_length=30)),
                ('cure_description', models.TextField()),
                ('cure_address', models.CharField(max_length=100)),
                ('hospital_id', models.IntegerField()),
                ('hospital_sections', models.CharField(max_length=40)),
                ('hospital_info', models.TextField()),
            ],
        ),
    ]
